library(magrittr)
library(rio)      
library(timetk)   
library(dplyr)    
library(tidyr)    
library(ggplot2) 
library(readr)
library(readxl)
library(forecast)
library(zoo)
library(rio) 
library(timetk)

#################
## Estatística ##
#################
~
if(!require(TeachingDemos)){install.packages("TeachingDemos")}
if(!require(EnvStats)){install.packages("EnvStats")}
if(!require(xtable)){install.packages("xtable")}
if(!require(stargazer)){install.packages("stargazer")}
if(!require(highcharter)){install.packages("highcharter")}
if(!require(quantmod)){install.packages("quantmod")}
if(!require(dygraphs)){install.packages("dygraphs")}
if(!require(tseries)){install.packages("tseries")}
if(!require(Quandl)){install.packages("Quandl")}
if(!require(nycflights13)){install.packages("nycflights13")}
if(!require(discreteRV)){install.packages("discreteRV")}
if(!require(aTSA)){install.packages("aTSA")}
if(!require(fGarch)){install.packages("fGarch")}
if(!require(fUnitRoots)){install.packages("fUnitRoots")}
if(!require(vars)){install.packages("vars")}
if(!require(MTS)){install.packages("MTS")}
if(!require(seasonal)){install.packages("seasonal")}
if(!require(urca)){install.packages("urca")}
if(!require(dynlm)){install.packages("dynlm")}
if(!require(tbl2xts)){install.packages("tbl2xts")}
if(!require(dlm)){install.packages("dlm")}
if(!require(stats)){install.packages("stats")}
if(!require(tcltk)){install.packages("tcltk")}
if(!require(PerformanceAnalytics)){install.packages("PerformanceAnalytics")}
if(!require(nortest)){install.packages("nortest")}
if(!require(scales)){install.packages("scales")}
if(!require(seasonalview)){install.packages("seasonalview")}
if(!require(stringr)){install.packages("stringr")}
if(!require(fma)){install.packages("fma")}